# -*- coding: utf-8 -*-
import csv

class ProcessBase:
    def __init__(self, outfile, period, titles, infile):
        self.outfile = outfile
        self.period = period
        self.titles = titles
        self.dict_titles = dict()
        for title in titles:
            self.dict_titles[title] = title
        self.outfile.write("# This file is automatically generated by make_tests")
        if infile is not None:
            self.outfile.write(" from \"" + infile + "\"")
        self.outfile.write("\n\n")

    # テストファイル１行出力メソッド
    # flag: True なら yml のセクション開始記号(-) を挿入する
    # xlate: True なら title を dist_titles に従って名称変更する
    def lineout(self, spaces, title, value, flag = False, xlate = True):
        # check for starting a new section
        if flag is True:
            self.outfile.write("-")
        for i in range(spaces):
            self.outfile.write(" ")
        if xlate is True:
            mytitle = self.dict_titles[title]
        else:
            mytitle = title
        self.outfile.write(mytitle)
        self.outfile.write(":")
        if value is not None:
            self.outfile.write(" ")
            self.outfile.write(value)
        self.outfile.write("\n")
